### ISSUE TITLE
why arms rotate with y-axis instead of z?

### ISSUE THREAD

**Issue by haobinyang** [vladmandic/human-vrm#2]
Could you explain why arms rotate with y-axis instead of z? @vladmandic

**Comment by vladmandic** [comment]
that how vrm model was defined. feel free to change, there is no hard reason for it.  
in general, this keypoints to vrm model is somewhat old and i haven't made any improvement to it in a while, been focused on a newer model.

**Comment by haobinyang** [comment]
> 

OK, thank you, I will try it.
